# Makefile for Beginning Linux Programming 3rd Edition
# Chapter 3

SIMPLE=simple_write simple_read
COPY=copy_system copy_block copy_stdio
DIR=printdir printdir2
MMAP=mmap

ALL= $(SIMPLE) $(COPY) $(DIR) $(MMAP)

all: $(ALL)

clean:
	@rm -f $(ALL) file.out records.dat *~
