all: fifo1 fifo2 fifo3 fifo4 pipe1 pipe2 pipe3 pipe4 pipe5 popen1 popen2 popen3 popen4 client server

client.o: client.h
server.o: client.h

clean:
	rm -f fifo1 fifo2 fifo3 fifo4 pipe1 pipe2 pipe3 pipe4 pipe5 popen1 popen2 popen3 popen4 client server /tmp/my_fifo *.o
