# ld-csv.sql

DELETE FROM loadtest;
#@ LOAD_CSV_STMT
LOAD DATA LOCAL INFILE 'data-csv.txt' INTO TABLE loadtest
#@ LOAD_CSV_OPTIONS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
#@ LOAD_CSV_OPTIONS
#@ LOAD_CSV_STMT
;

SELECT * FROM loadtest;
