# ld-tab.sql

DELETE FROM loadtest;
#@ SAME_AS_DEFAULT_STMT
LOAD DATA LOCAL INFILE 'data-tab.txt' INTO TABLE loadtest
#@ SAME_AS_DEFAULT_OPTIONS
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
#@ SAME_AS_DEFAULT_OPTIONS
#@ SAME_AS_DEFAULT_STMT
;
DELETE FROM loadtest;
LOAD DATA LOCAL INFILE 'data-tab.txt' INTO TABLE loadtest
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
;

SELECT * FROM loadtest;
