# mark_log.sql

DROP TABLE IF EXISTS `mark_log`;
#@ _CREATE_TABLE_
CREATE TABLE `mark_log` (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `message` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
#@ _CREATE_TABLE_

