# Makefile for Beginning Linux Programming 4th Edition
# Chapter 5

MENU=menu1 menu2 menu3 menu4 menu5
TERMINAL=sizeterm badterm password
KBHIT=kbhit

LDFLAGS=-lncurses

ALL= $(MENU) $(TERMINAL) $(KBHIT)

all: $(ALL)

clean:
	@rm -f $(ALL) *~
