all: thread1 thread2 thread3 thread3a thread4 thread5 thread6 thread6a thread7 thread8 thread8a

CFLAGS=-D_REENTRANT
LDFLAGS=-lpthread

clean:
	rm -f thread1 thread2 thread3 thread3a thread4 thread5 thread6 thread6a thread7 thread7a thread8 thread8a


